### PR TITLE
Add unrestricted option

### PR DESCRIPTION
**Pull request by Sasanidas**
Ripgrep have an option to ignore .gitignore files, sometimes it is useful (at least for me) to use this kind of approach.
Thank you

### CODE REVIEW

**Comment by dajva** [comment]
I believe `--unrestricted` is essentially the same as `--no-ignore` that is a available as a *toggle* command in the results buffer (bound to `i`). Is that not enough for your use case?

**Comment by dajva** [comment]
Oh, just saw that `--no-ignore` is actually present in the menu as well. There is a bug here lurking though so I am not sure that will stay but I will try to when fixing that bug. So, what remains then is if you are aware of any differences between *a single* `--unrestricted` and `--no-ignore`. My understanding is that they are the same.

**Comment by Sasanidas** [comment]
> Oh, just saw that `--no-ignore` is actually present in the menu as well. There is a bug here lurking though so I am not sure that will stay but I will try to when fixing that bug. So, what remains then is if you are aware of any differences between _a single_ `--unrestricted` and `--no-ignore`. My understanding is that they are the same.

You are right, this is what the documentation say [source](https://github.com/BurntSushi/ripgrep/blob/master/doc/rg.1.txt.tpl#L176):

    * '-u' is equivalent to '--no-ignore'.
    * '-uu' is equivalent to '--no-ignore --hidden'.
    * '-uuu' is equivalent to '--no-ignore --hidden --binary'.

So, maybe the option to add would be --binary?
Thank you

**Comment by dajva** [comment]
Sure, add it and I merge it.

**Comment by dajva** [comment]
The `--no-ignore` flag should now be handled correctly in the menu with the fix in 6a5700d42b84cee4da16636e987f9d11d9eaf40f.

**Pull request closed without merging**
